### ISSUE TITLE
pyetcd.EtcdException: the JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by dylan-evans** [twindb/pyetcd#6]
```
Traceback (most recent call last):
  File "service.py", line 107, in <module>
    iface = Interface()
  File "service.py", line 16, in __init__
    amqp_url = etc.read("/services/amqp-url").node["value"]
  File "C:\Program Files\Python35\lib\site-packages\pyetcd\client.py", line 102, in read
    return self._request_key(key, params=kwargs)
  File "C:\Program Files\Python35\lib\site-packages\pyetcd\client.py", line 290, in _request_key
    return self._request_call(uri, method=method, **kwargs)
  File "C:\Program Files\Python35\lib\site-packages\pyetcd\client.py", line 302, in _request_call
    return EtcdResult(getattr(requests, method)(url, **kwargs))
  File "C:\Program Files\Python35\lib\site-packages\pyetcd\__init__.py", line 267, in __init__
    raise EtcdException(err)
pyetcd.EtcdException: the JSON object must be str, not 'bytes'

```
Came across this issue on Python 3, the response content is encoded as 'bytes' in version 3 and needs to be decoded to str.

**Comment by dylan-evans** [comment]
Thought i needed an issue for my pull request for some reason, never mind.
